//ENTRY(ID,  var,                            unit,  name,                   minvalue,    maxvalue  )

ENTRY('1', sensorData.voltage,                "V",  "battery voltage",           0.0,        25.0  )
ENTRY('2', motor1.shaft_angle,              "rad",  "shaft 1 angle",           -6.28,        6.28  )
ENTRY('3', motor1.shaft_velocity,         "rad/s",  "shaft 1 velocity",        -50.0,        50.0  )
ENTRY('4', actuator.torque1,                  "A",  "motor 1 current",          -1.0,         1.0  )
ENTRY('5', motor2.shaft_angle,              "rad",  "shaft 2 angle",           -6.28,        6.28  )
ENTRY('6', motor2.shaft_velocity,         "rad/s",  "shaft 2 velocity",        -50.0,        50.0  )
ENTRY('7', actuator.torque2,                  "A",  "motor 2 current",          -1.0,         1.0  )
ENTRY('8', sensorData.pitchAngleAcc,          "°",  "pitch acc",              -180.0,       180.0  )
ENTRY('9', sensorData.rollAngleAcc,           "°",  "roll acc",               -180.0,       180.0  )
ENTRY('0', sensorData.pitchAngle,             "°",  "pitch",                  -180.0,       180.0  )
ENTRY('l', sensorData.rollAngle,              "°",  "roll",                   -180.0,       180.0  )
ENTRY('q', sensorData.acc.x,                  "g",  "acc x",                    -1.0,         1.0  )
ENTRY('w', sensorData.acc.y,                  "g",  "acc y",                    -1.0,         1.0  )
ENTRY('e', sensorData.acc.z,                  "g",  "acc z",                    -1.0,         1.0  )
ENTRY('r', sensorData.gyro.x,               "°/s",  "gyro x",                 -250.0,       250.0  )
ENTRY('t', sensorData.gyro.y,               "°/s",  "gyro y",                 -250.0,       250.0  )
ENTRY('z', sensorData.gyro.z,               "°/s",  "gyro z",                 -250.0,       250.0  )
ENTRY('u', sensorData.magnet.x,              "µT",  "magnet x",               -100.0,       100.0  )
ENTRY('i', sensorData.magnet.y,              "µT",  "magnet y",               -100.0,       100.0  )
ENTRY('o', sensorData.magnet.z,              "µT",  "magnet z",               -100.0,       100.0  )
ENTRY('p', sensorData.temp,                  "°C",  "imu temperature",           0.0,        40.0  )
ENTRY('a', sensorData.taskTime[0][ttmin],    "us", "slow task min time",         0.0,      5000.0  )
ENTRY('s', sensorData.taskTime[0][ttmax],    "us", "slow task max time",         0.0,      5000.0  )
ENTRY('d', sensorData.taskTime[0][ttavg],    "us", "slow task avg time",         0.0,      5000.0  )
ENTRY('f', sensorData.taskTime[1][ttmin],    "us", "fast task min time",         0.0,       500.0  )
ENTRY('g', sensorData.taskTime[1][ttmax],    "us", "fast task max time",         0.0,       500.0  )
ENTRY('h', sensorData.taskTime[1][ttavg],    "us", "fast task avg time",         0.0,       500.0  )
ENTRY('y', joystickReport.x,                   "", "joystick x",                 0.0,       255.0  )
ENTRY('x', joystickReport.y,                   "", "joystick y",                 0.0,       255.0  )
ENTRY('c', joystickReport.z,                   "", "joystick z",                 0.0,       255.0  )
ENTRY('v', joystickReport.rz,                  "", "joystick rz",                0.0,       255.0  )
ENTRY('b', joystickReport.buttons,             "", "joystick buttons",           0.0,      4096.0  )
ENTRY('n', joystickReport.hat,                 "", "joystick hat",               0.0,       255.0  )
ENTRY('m', joystickTimeout,                    "", "joystick timeout",           0.0,       100.0  )


ENTRY(0,   actuator.disabled,                 "-",  "end of table",              0.0,         0.0  )
