//ENTRY(ID,  var,                            unit,  name,                   minvalue,    maxvalue  )

ENTRY('1', motor.shaft_angle,               "rad",  "shaft angle",             -6.28,        6.28  )
ENTRY('2', motor.shaft_velocity,          "rad/s",  "shaft velocity",          -50.0,        50.0  )
ENTRY('3', actuator.torque,                   "A",  "motor current",            -1.0,         1.0  )
ENTRY('4', sensorData.voltage,                "V",  "battery voltage",           0.0,        25.0  )
ENTRY('q', sensorData.acc.x,                  "g",  "acc x",                    -1.0,         1.0  )
ENTRY('w', sensorData.acc.y,                  "g",  "acc y",                    -1.0,         1.0  )
ENTRY('e', sensorData.acc.z,                  "g",  "acc z",                    -1.0,         1.0  )
ENTRY('r', sensorData.gyro.x,               "°/s",  "gyro x",                 -250.0,       250.0  )
ENTRY('t', sensorData.gyro.y,               "°/s",  "gyro y",                 -250.0,       250.0  )
ENTRY('z', sensorData.gyro.z,               "°/s",  "gyro z",                 -250.0,       250.0  )
ENTRY('u', sensorData.magnet.x,              "µT",  "magnet x",               -100.0,       100.0  )
ENTRY('i', sensorData.magnet.y,              "µT",  "magnet y",               -100.0,       100.0  )
ENTRY('o', sensorData.magnet.z,              "µT",  "magnet z",               -100.0,       100.0  )
ENTRY('p', sensorData.temp,                  "°C",  "imu temperature",           0.0,        40.0  )
ENTRY('a', sensorData.taskTime[0][ttmin],    "us", "slow task min time",         0.0,      5000.0  )
ENTRY('s', sensorData.taskTime[0][ttmax],    "us", "slow task max time",         0.0,      5000.0  )
ENTRY('d', sensorData.taskTime[0][ttavg],    "us", "slow task avg time",         0.0,      5000.0  )
ENTRY('f', sensorData.taskTime[1][ttmin],    "us", "fast task min time",         0.0,       500.0  )
ENTRY('g', sensorData.taskTime[1][ttmax],    "us", "fast task max time",         0.0,       500.0  )
ENTRY('h', sensorData.taskTime[1][ttavg],    "us", "fast task avg time",         0.0,       500.0  )
ENTRY('y', joystickReport.x,                   "", "joystick x",                 0.0,       255.0  )
ENTRY('x', joystickReport.y,                   "", "joystick y",                 0.0,       255.0  )
ENTRY('c', joystickReport.z,                   "", "joystick z",                 0.0,       255.0  )
ENTRY('v', joystickReport.rz,                  "", "joystick rz",                0.0,       255.0  )
ENTRY('b', joystickReport.buttons,             "", "joystick buttons",           0.0,      4096.0  )
ENTRY('n', joystickTimeout,                    "", "joystick timeout",           0.0,       100.0  )


ENTRY(0,   actuator.disabled,                 "-",  "end of table",              0.0,         0.0  )
