//ENTRY(ID, var,                     increment,    unit,    name                              )

ENTRY('1',  motor1.zero_electric_angle,  0.01,    "rad",    "M1 zero electric angle"          )
ENTRY('2',  motor2.zero_electric_angle,  0.01,    "rad",    "M2 zero electric angle"          )
ENTRY('3',  controlPara.iPartSpeed,      0.01,       "",    "i part speed"                    )
ENTRY('4',  controlPara.pPartSpeed,      0.01,       "",    "p part speed"                    )
ENTRY('5',  controlPara.pPartPitch,      0.01,       "",    "p part pitch"                    )
ENTRY('6',  controlPara.dPartPitch,      0.01,       "",    "d part pitch"                    )
ENTRY('7',  controlPara.pitchWP,         0.01,       "",    "pitch wp"                        )
ENTRY('8',  controlPara.speedFilter,      1.0,     "ms",    "speed filter"                    )
ENTRY('9',  controlPara.iPartSpeedRoll,  0.01,       "",    "i part speed roll"               )
ENTRY('0',  controlPara.pPartSpeedRoll,  0.01,       "",    "p part speed roll"               )
ENTRY('a',  controlPara.pPartRoll,       0.01,       "",    "p part roll"                     )
ENTRY('s',  controlPara.dPartRoll,       0.01,       "",    "d part roll"                     )
ENTRY('d',  controlPara.rollWP,          0.01,       "",    "roll wp"                         )
ENTRY('f',  controlPara.speedRollFilter,  1.0,     "ms",    "speed roll filter"               )

ENTRY(  0,  controlPara.dPartPitch,      0.01,       "",    "end of table"                    )
